# Generated by Django 4.0.4 on 2022-05-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='publicado',
            field=models.DateField(default=0),
        ),
    ]
