# Generated by Django 4.0.4 on 2022-05-03 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_blog_publicado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name': 'Profesor', 'verbose_name_plural': 'profesores'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='publicado',
        ),
    ]
